package com.hopline.WebApp.model.dao;
// default package
// Generated 3 Jan, 2017 4:42:03 PM by Hibernate Tools 5.2.0.Beta1

import java.util.HashSet;
import java.util.Set;

/**
 * AddonGroup generated by hbm2java
 */
public class AddonGroup implements java.io.Serializable {

	private Integer idaddonGroup;
	private String name;
	private String desc;
	private String radioYn;
	private Integer minSelect;
	private Set<AddOn> addOns = new HashSet<AddOn>(0);
	private Set<Product> products = new HashSet<Product>(0);

	public AddonGroup() {
	}

	public AddonGroup(String radioYn) {
		this.radioYn = radioYn;
	}

	public AddonGroup(String name, String desc, String radioYn, Integer minSelect, Set<AddOn> addOns,
			Set<Product> products) {
		this.name = name;
		this.desc = desc;
		this.radioYn = radioYn;
		this.minSelect = minSelect;
		this.addOns = addOns;
		this.products = products;
	}

	public Integer getIdaddonGroup() {
		return this.idaddonGroup;
	}

	public void setIdaddonGroup(Integer idaddonGroup) {
		this.idaddonGroup = idaddonGroup;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDesc() {
		return this.desc;
	}

	public void setDesc(String desc) {
		this.desc = desc;
	}

	public String getRadioYn() {
		return this.radioYn;
	}

	public void setRadioYn(String radioYn) {
		this.radioYn = radioYn;
	}

	public Integer getMinSelect() {
		return this.minSelect;
	}

	public void setMinSelect(Integer minSelect) {
		this.minSelect = minSelect;
	}

	public Set<AddOn> getAddOns() {
		return this.addOns;
	}

	public void setAddOns(Set<AddOn> addOns) {
		this.addOns = addOns;
	}

	public Set<Product> getProducts() {
		return this.products;
	}

	public void setProducts(Set<Product> products) {
		this.products = products;
	}

}
