package com.hopline.WebApp.model.dao;
// Generated 28 Sep, 2016 12:38:57 AM by Hibernate Tools 5.2.0.Beta1

import java.util.HashSet;
import java.util.Set;

/**
 * AddOn generated by hbm2java
 */
public class AddOn implements java.io.Serializable {

	private Integer idaddOn;
	private String name;
	private long price;
	private String stockYn;
	private Set products = new HashSet(0);

	public AddOn() {
	}

	public AddOn(String name, long price, String stockYn) {
		this.name = name;
		this.price = price;
		this.stockYn = stockYn;
	}

	public AddOn(String name, long price, String stockYn, Set products) {
		this.name = name;
		this.price = price;
		this.stockYn = stockYn;
		this.products = products;
	}

	public Integer getIdaddOn() {
		return this.idaddOn;
	}

	public void setIdaddOn(Integer idaddOn) {
		this.idaddOn = idaddOn;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public long getPrice() {
		return this.price;
	}

	public void setPrice(long price) {
		this.price = price;
	}

	public String getStockYn() {
		return this.stockYn;
	}

	public void setStockYn(String stockYn) {
		this.stockYn = stockYn;
	}

	public Set getProducts() {
		return this.products;
	}

	public void setProducts(Set products) {
		this.products = products;
	}

}
