package com.hopline.WebApp.model.dao;
// Generated 1 Oct, 2016 11:23:02 PM by Hibernate Tools 5.2.0.Beta1

import java.util.HashSet;
import java.util.Set;

/**
 * AddOn generated by hbm2java
 */
public class AddOn implements java.io.Serializable {

	private Integer idaddOn;
	private String name;
	private long price;
	private String stockYn;
	private Set<OrderProduct>  orderProducts = new HashSet<OrderProduct>();
	private Set<Product>  products = new HashSet<Product>();

	public AddOn() {
	}

	public AddOn(String name, long price, String stockYn) {
		this.name = name;
		this.price = price;
		this.stockYn = stockYn;
	}

	public AddOn(String name, long price, String stockYn, Set<OrderProduct>  orderProducts, Set<Product>  products) {
		this.name = name;
		this.price = price;
		this.stockYn = stockYn;
		this.orderProducts = orderProducts;
		this.products = products;
	}

	public Integer getIdaddOn() {
		return this.idaddOn;
	}

	public void setIdaddOn(Integer idaddOn) {
		this.idaddOn = idaddOn;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public long getPrice() {
		return this.price;
	}

	public void setPrice(long price) {
		this.price = price;
	}

	public String getStockYn() {
		return this.stockYn;
	}

	public void setStockYn(String stockYn) {
		this.stockYn = stockYn;
	}

	public Set<OrderProduct>  getOrderProducts() {
		return this.orderProducts;
	}

	public void setOrderProducts(Set<OrderProduct>  orderProducts) {
		this.orderProducts = orderProducts;
	}

	public Set<Product>  getProducts() {
		return this.products;
	}

	public void setProducts(Set<Product>  products) {
		this.products = products;
	}

}
