package com.hopline.WebApp.model.dao;
// Generated 6 Oct, 2016 1:14:11 AM by Hibernate Tools 5.2.0.Beta1

import java.util.HashSet;
import java.util.Set;

/**
 * Category generated by hbm2java
 */
public class Category implements java.io.Serializable {

	private Integer idcategory;
	private Shop shop;
	private String name;
	private String subCategoryName;
	private int sortId;
	private String imgUrl;
	private Set<Product> products = new HashSet<Product>(0);

	public Category() {
	}

	public Category(Shop shop, String name, int sortId) {
		this.shop = shop;
		this.name = name;
		this.sortId = sortId;
	}

	public Category(Shop shop, String name, String subCategoryName, int sortId, Set<Product> products) {
		this.shop = shop;
		this.name = name;
		this.subCategoryName = subCategoryName;
		this.sortId = sortId;
		this.products = products;
	}

	public Integer getIdcategory() {
		return this.idcategory;
	}

	public void setIdcategory(Integer idcategory) {
		this.idcategory = idcategory;
	}

	public Shop getShop() {
		return this.shop;
	}

	public void setShop(Shop shop) {
		this.shop = shop;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSubCategoryName() {
		return this.subCategoryName;
	}

	public void setSubCategoryName(String subCategoryName) {
		this.subCategoryName = subCategoryName;
	}

	public int getSortId() {
		return this.sortId;
	}

	public void setSortId(int sortId) {
		this.sortId = sortId;
	}

	public Set<Product> getProducts() {
		return this.products;
	}

	public void setProducts(Set<Product> products) {
		this.products = products;
	}

	public String getImgUrl() {
		return imgUrl;
	}

	public void setImgUrl(String imgUrl) {
		this.imgUrl = imgUrl;
	}

}
