package com.hopline.WebApp.model.dao;
// Generated 1 Oct, 2016 11:23:02 PM by Hibernate Tools 5.2.0.Beta1

import java.util.HashSet;
import java.util.Set;

/**
 * Category generated by hbm2java
 */
public class Category implements java.io.Serializable {

	private Integer idcategory;
	private String name;
	private int sortId;
	private Set<Product> products = new HashSet<Product>();

	public Category() {
	}

	public Category(String name, int sortId) {
		this.name = name;
		this.sortId = sortId;
	}

	public Category(String name, int sortId, Set<Product> products) {
		this.name = name;
		this.sortId = sortId;
		this.products = products;
	}

	public Integer getIdcategory() {
		return this.idcategory;
	}

	public void setIdcategory(Integer idcategory) {
		this.idcategory = idcategory;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getSortId() {
		return this.sortId;
	}

	public void setSortId(int sortId) {
		this.sortId = sortId;
	}

	public Set<Product> getProducts() {
		return this.products;
	}

	public void setProducts(Set<Product> products) {
		this.products = products;
	}

}
