package com.hopline.WebApp.model.dao;

// Generated 23 Nov, 2016 10:51:45 PM by Hibernate Tools 5.2.0.Beta1

import java.util.Date;

/**
 * OfflineOrderLog generated by hbm2java
 */
public class OfflineOrderLog implements java.io.Serializable {

	private Integer idofflineOrderLog;
	private String ordersJson;
	private Date insertTime;

	public OfflineOrderLog() {
	}

	public OfflineOrderLog(String ordersJson, Date insertTime) {
		this.ordersJson = ordersJson;
		this.insertTime = insertTime;
	}

	public Integer getIdofflineOrderLog() {
		return this.idofflineOrderLog;
	}

	public void setIdofflineOrderLog(Integer idofflineOrderLog) {
		this.idofflineOrderLog = idofflineOrderLog;
	}

	public String getOrdersJson() {
		return this.ordersJson;
	}

	public void setOrdersJson(String ordersJson) {
		this.ordersJson = ordersJson;
	}

	public Date getInsertTime() {
		return this.insertTime;
	}

	public void setInsertTime(Date insertTime) {
		this.insertTime = insertTime;
	}

}
