package com.hopline.WebApp.model.dao;
// Generated 6 Oct, 2016 1:14:11 AM by Hibernate Tools 5.2.0.Beta1

import java.util.HashSet;
import java.util.Set;

/**
 * OrderProduct generated by hbm2java
 */
public class OrderProduct implements java.io.Serializable {

	private Integer idorderProduct;
	private Order order;
	private Product product;
	private int count;
	private Set<OrderProductAddon> orderProductAddons = new HashSet<OrderProductAddon>(0);
	public Integer getIdorderProduct() {
		return idorderProduct;
	}
	public void setIdorderProduct(Integer idorderProduct) {
		this.idorderProduct = idorderProduct;
	}
	public Order getOrder() {
		return order;
	}
	public void setOrder(Order order) {
		this.order = order;
	}
	public Product getProduct() {
		return product;
	}
	public void setProduct(Product product) {
		this.product = product;
	}
	public int getCount() {
		return count;
	}
	public void setCount(int count) {
		this.count = count;
	}
	public Set<OrderProductAddon> getOrderProductAddons() {
		return orderProductAddons;
	}
	public void setOrderProductAddons(Set<OrderProductAddon> orderProductAddons) {
		this.orderProductAddons = orderProductAddons;
	}

	
}
