package com.hopline.WebApp.model.dao;
// Generated 6 Oct, 2016 1:14:11 AM by Hibernate Tools 5.2.0.Beta1

import java.util.Date;

/**
 * OrderStatusLog generated by hbm2java
 */
public class OrderStatusLog implements java.io.Serializable {

	private Integer orderStatusLogid;
	private Date timestamp;
	private int orderId;
	private String orderStatus;

	public OrderStatusLog() {
	}

	public OrderStatusLog(Integer orderStatusLogid, int orderId, String orderStatus) {
		this.orderStatusLogid = orderStatusLogid;
		this.orderId = orderId;
		this.orderStatus = orderStatus;
	}

	public Integer getOrderStatusLogid() {
		return this.orderStatusLogid;
	}

	public void setOrderStatusLogid(Integer orderStatusLogid) {
		this.orderStatusLogid = orderStatusLogid;
	}

	public Date getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

	public int getOrderId() {
		return this.orderId;
	}

	public void setOrderId(int orderId) {
		this.orderId = orderId;
	}

	public String getOrderStatus() {
		return this.orderStatus;
	}

	public void setOrderStatus(String orderStatus) {
		this.orderStatus = orderStatus;
	}

}
