package com.hopline.WebApp.model.dao;
// Generated 6 Oct, 2016 1:14:11 AM by Hibernate Tools 5.2.0.Beta1

import java.util.HashSet;
import java.util.Set;

/**
 * OrderProduct generated by hbm2java
 */
public class OrderProduct implements java.io.Serializable {

	private Integer idorderProduct;
	private Order order;
	private Product product;
	private int count;
	private Set<AddOn> addOns = new HashSet<AddOn>(0);

	public OrderProduct() {
	}

	public OrderProduct(Order order, Product product, int count) {
		this.order = order;
		this.product = product;
		this.count = count;
	}

	public OrderProduct(Order order, Product product, int count, Set<AddOn> addOns) {
		this.order = order;
		this.product = product;
		this.count = count;
		this.addOns = addOns;
	}

	public Integer getIdorderProduct() {
		return this.idorderProduct;
	}

	public void setIdorderProduct(Integer idorderProduct) {
		this.idorderProduct = idorderProduct;
	}

	public Order getOrder() {
		return this.order;
	}

	public void setOrder(Order order) {
		this.order = order;
	}

	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	public int getCount() {
		return this.count;
	}

	public void setCount(int count) {
		this.count = count;
	}

	public Set<AddOn> getAddOns() {
		return this.addOns;
	}

	public void setAddOns(Set<AddOn> addOns) {
		this.addOns = addOns;
	}

}
