package com.hopline.WebApp.model.dao;
// Generated Oct 8, 2016 12:01:47 AM by Hibernate Tools 5.2.0.Beta1

/**
 * OrderProductAddon generated by hbm2java
 */
public class OrderProductAddon implements java.io.Serializable {

	private Integer orderProductAddonId;
	private AddOn addOn;
	private OrderProduct orderProduct;

	public OrderProductAddon() {
	}

	public OrderProductAddon(AddOn addOn, OrderProduct orderProduct) {
		this.addOn = addOn;
		this.orderProduct = orderProduct;
	}

	public Integer getOrderProductAddonId() {
		return this.orderProductAddonId;
	}

	public void setOrderProductAddonId(Integer orderProductAddonId) {
		this.orderProductAddonId = orderProductAddonId;
	}

	public AddOn getAddOn() {
		return this.addOn;
	}

	public void setAddOn(AddOn addOn) {
		this.addOn = addOn;
	}

	public OrderProduct getOrderProduct() {
		return this.orderProduct;
	}

	public void setOrderProduct(OrderProduct orderProduct) {
		this.orderProduct = orderProduct;
	}

}
