package com.hopline.WebApp.model.dao;
// Generated 6 Oct, 2016 1:14:11 AM by Hibernate Tools 5.2.0.Beta1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product implements java.io.Serializable {

	private Integer productId;
	private String name;
	private String shortDesc;
	private String longDesc;
	private BigDecimal price;
	private String vegYn;
	private String stockYn;
	private String singleAddonYN;
	private String timeUnavailable;
	private Set<AddOn> addOns = new HashSet<AddOn>(0);
	private Set<OrderProduct> orderProducts = new HashSet<OrderProduct>(0);
	private Set<Category> categories = new HashSet<Category>(0);

	public Product() {
	}

	public Product(String name, BigDecimal price, String vegYn, String stockYn) {
		this.name = name;
		this.price = price;
		this.vegYn = vegYn;
		this.stockYn = stockYn;
	}

	public Product(String name, String shortDesc, String longDesc, BigDecimal price, String vegYn, String stockYn,
			Set<AddOn> addOns, Set<OrderProduct> orderProducts, Set<Category> categories) {
		this.name = name;
		this.shortDesc = shortDesc;
		this.longDesc = longDesc;
		this.price = price;
		this.vegYn = vegYn;
		this.stockYn = stockYn;
		this.addOns = addOns;
		this.orderProducts = orderProducts;
		this.categories = categories;
	}

	public Integer getProductId() {
		return this.productId;
	}

	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getShortDesc() {
		return this.shortDesc;
	}

	public void setShortDesc(String shortDesc) {
		this.shortDesc = shortDesc;
	}

	public String getLongDesc() {
		return this.longDesc;
	}

	public void setLongDesc(String longDesc) {
		this.longDesc = longDesc;
	}

	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	public String getVegYn() {
		return this.vegYn;
	}

	public void setVegYn(String vegYn) {
		this.vegYn = vegYn;
	}

	public String getStockYn() {
		return this.stockYn;
	}

	public void setStockYn(String stockYn) {
		this.stockYn = stockYn;
	}

	public Set<AddOn> getAddOns() {
		return this.addOns;
	}

	public void setAddOns(Set<AddOn> addOns) {
		this.addOns = addOns;
	}

	public Set<OrderProduct> getOrderProducts() {
		return this.orderProducts;
	}

	public void setOrderProducts(Set<OrderProduct> orderProducts) {
		this.orderProducts = orderProducts;
	}

	public Set<Category> getCategories() {
		return this.categories;
	}

	public void setCategories(Set<Category> categories) {
		this.categories = categories;
	}

	public String getSingleAddonYN() {
		return singleAddonYN;
	}

	public void setSingleAddonYN(String singleAddonYN) {
		this.singleAddonYN = singleAddonYN;
	}

	public String getTimeUnavailable() {
		return timeUnavailable;
	}

	public void setTimeUnavailable(String timeUnavailable) {
		this.timeUnavailable = timeUnavailable;
	}

	

}
