package com.hopline.WebApp.model.dao;
// Generated 6 Oct, 2016 1:14:11 AM by Hibernate Tools 5.2.0.Beta1

import java.util.Date;

/**
 * SecurityToken generated by hbm2java
 */
public class SecurityToken implements java.io.Serializable {

	private Integer idSecurityToken;
	private User user;
	private String securityToken;
	private Date createTs;

	public SecurityToken() {
	}

	public SecurityToken(User user, String securityToken, Date createTs) {
		this.user = user;
		this.securityToken = securityToken;
		this.createTs = createTs;
	}

	public Integer getIdSecurityToken() {
		return this.idSecurityToken;
	}

	public void setIdSecurityToken(Integer idSecurityToken) {
		this.idSecurityToken = idSecurityToken;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getSecurityToken() {
		return this.securityToken;
	}

	public void setSecurityToken(String securityToken) {
		this.securityToken = securityToken;
	}

	public Date getCreateTs() {
		return this.createTs;
	}

	public void setCreateTs(Date createTs) {
		this.createTs = createTs;
	}

}
