package com.hopline.WebApp.model.dao;
// Generated 6 Oct, 2016 1:14:11 AM by Hibernate Tools 5.2.0.Beta1

import java.util.HashSet;
import java.util.Set;

/**
 * Shop generated by hbm2java
 */
public class Shop implements java.io.Serializable {

	private Integer idshop;
	private String shopName;
	private String phone;
	private String imgUrl;
	private String activeYn;
	private Set<Category> categories = new HashSet<Category>(0);
	private Set<Order> orders = new HashSet<Order>(0);

	public Shop() {
	}

	public Shop(String shopName, String activeYn) {
		this.shopName = shopName;
		this.activeYn = activeYn;
	}

	public Shop(String shopName, String phone, String imgUrl, String activeYn, Set<Category> categories,
			Set<Order> orders) {
		this.shopName = shopName;
		this.phone = phone;
		this.imgUrl = imgUrl;
		this.activeYn = activeYn;
		this.categories = categories;
		this.orders = orders;
	}

	public Integer getIdshop() {
		return this.idshop;
	}

	public void setIdshop(Integer idshop) {
		this.idshop = idshop;
	}

	public String getShopName() {
		return this.shopName;
	}

	public void setShopName(String shopName) {
		this.shopName = shopName;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getImgUrl() {
		return this.imgUrl;
	}

	public void setImgUrl(String imgUrl) {
		this.imgUrl = imgUrl;
	}

	public String getActiveYn() {
		return this.activeYn;
	}

	public void setActiveYn(String activeYn) {
		this.activeYn = activeYn;
	}

	public Set<Category> getCategories() {
		return this.categories;
	}

	public void setCategories(Set<Category> categories) {
		this.categories = categories;
	}

	public Set<Order> getOrders() {
		return this.orders;
	}

	public void setOrders(Set<Order> orders) {
		this.orders = orders;
	}

}
