package com.hopline.vendorServices.model;

// Generated 23 Nov, 2016 10:51:45 PM by Hibernate Tools 5.2.0.Beta1

import java.util.Date;

/**
 * OfflineOrderLog generated by hbm2java
 */
public class OfflineOrderLogTo implements java.io.Serializable {

	private String ordersJson;
	private boolean success;
	public String getOrdersJson() {
		return ordersJson;
	}
	public void setOrdersJson(String ordersJson) {
		this.ordersJson = ordersJson;
	}
	public boolean isSuccess() {
		return success;
	}
	public void setSuccess(boolean success) {
		this.success = success;
	}



}
