package com.hopline.WebApp.model.vo;

//Generated 20 Dec, 2016 3:07:20 AM by Hibernate Tools 5.2.0.Beta1

/**
 * Feedback generated by hbm2java
 */
public class FeedbackVo implements java.io.Serializable {

	private int idfeedback;
	private int userId;
	private Integer rating;
	private String fedText;

	public FeedbackVo() {
	}



	public int getIdfeedback() {
		return this.idfeedback;
	}

	public void setIdfeedback(int idfeedback) {
		this.idfeedback = idfeedback;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public Integer getRating() {
		return this.rating;
	}

	public void setRating(Integer rating) {
		this.rating = rating;
	}

	public String getFedText() {
		return this.fedText;
	}

	public void setFedText(String fedText) {
		this.fedText = fedText;
	}

}
