package com.hopline.WebApp.model.vo;
// Generated Oct 8, 2016 12:01:47 AM by Hibernate Tools 5.2.0.Beta1

/**
 * OrderProductAddon generated by hbm2java
 */
public class OrderProductAddonVo implements java.io.Serializable {

	private Integer orderProductAddonId;
	private AddOnVo addOn;

	public Integer getOrderProductAddonId() {
		return orderProductAddonId;
	}
	public void setOrderProductAddonId(Integer orderProductAddonId) {
		this.orderProductAddonId = orderProductAddonId;
	}
	public AddOnVo getAddOn() {
		return addOn;
	}
	public void setAddOn(AddOnVo addOn) {
		this.addOn = addOn;
	}
}
