package com.hoplineVendorServices.model;
// Generated Oct 8, 2016 12:01:47 AM by Hibernate Tools 5.2.0.Beta1

/**
 * OrderProductAddon generated by hbm2java
 */
public class OrderProductAddonTo implements java.io.Serializable {

	private Integer orderProductAddonId;
	private AddOnTo addOn;

	public Integer getOrderProductAddonId() {
		return orderProductAddonId;
	}
	public void setOrderProductAddonId(Integer orderProductAddonId) {
		this.orderProductAddonId = orderProductAddonId;
	}
	public AddOnTo getAddOn() {
		return addOn;
	}
	public void setAddOn(AddOnTo addOn) {
		this.addOn = addOn;
	}
}
